### ISSUE TITLE
Should single nested items get a newline before them?

### ISSUE THREAD

**Issue by corysimmons** [ntwb/stylelint-config-wordpress#21]
```scss
.foo {
  
  .bar {
  
    .baz {
      color: red;
    }
  }
}
```

looks weird and unintended. is this part of the wpcs css spec?
