### ISSUE TITLE
Add `selector-attribute-operator-space-*` rules

### ISSUE THREAD

**Issue by ntwb** [ntwb/stylelint-config-wordpress#51]
Via https://github.com/stylelint/stylelint/pull/1147

```js
"selector-attribute-operator-space-after": "never",
"selector-attribute-operator-space-before": "never",
```

See https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#selectors

Correct:
```css
input[type="text"] {
    line-height: 1.1;
}
```

Incorrect
```css
input[type=text] {
    line-height: 1.1;
}
```
