### ISSUE TITLE
Add `no-extra-semicolons` rule

### ISSUE THREAD

**Issue by ntwb** [ntwb/stylelint-config-wordpress#52]
```js
"no-extra-semicolons": true,
```

See https://github.com/stylelint/stylelint/tree/master/src/rules/no-extra-semicolons

Correct:
```css
.foo {
  color: pink;
}
```

Incorrect:
```css
.foo {
  color: pink;;
}
```
