### ISSUE TITLE
Add `comment-empty-line-before` rule

### ISSUE THREAD

**Issue by ntwb** [ntwb/stylelint-config-wordpress#56]
> https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#commenting
> > _"Section/subsection headers should have newlines before and after. Inline comments should not have empty newlines separating the comment from the item to which it relates."_

The following patterns are _not_ considered warnings:
```css
/**
* #.# Section title
*
* Description of section, whether or not it has media queries, etc.
*/

.selector {
  float: left;
}


/**
* #.# Another section title
*
* Description of section, whether or not it has media queries, long comments
* should manually break the line length at 80 characters.
*/

.selector {
  float: right;
}

/* This is a comment about this selector */
.another-selector {
  position: absolute;
  top: 0 !important; /* I should explain why this is so !important */
}
```

The following patterns are considered warnings:
```css
/**
* #.# Section title
*
* Description of section, whether or not it has media queries, etc.
*/
.selector {
  float: left;
}
/**
* #.# Another section title
*
* Description of section, whether or not it has media queries, long comments
* should manually break the line length at 80 characters.
*/
.selector {
  float: right;
}

/* This is a comment about this selector */

.another-selector {
  position: absolute;
  top: 0 !important; /* I should explain why this is so !important */
}
```
