### ISSUE TITLE
Add `selector-attribute-quotes` rule

### ISSUE THREAD

**Issue by ntwb** [ntwb/stylelint-config-wordpress#58]
Via https://github.com/stylelint/stylelint/issues/1137

https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#selectors

Correct:
```css
input[type="text"] {
    line-height: 1.1;
}
```

Incorrect:
```css
input[type=text] {
    line-height: 1.1;
}

input[type='text'] {
    line-height: 1.1;
}
```
